### ISSUE TITLE
Thermo/Bubble Plots 

### ISSUE THREAD

**Issue by aokieh** [madamic/zynq_tdc#2]
Hello

I see that in the figures subfolder, there are plots for the delay line showing the signal propagation but the source code isn't available. Is there any way you could make that available alongside the other simulations?

https://github.com/madamic/zynq_tdc/tree/master/figs/AXITDC/TDCcore/delayLine

Best, 
Ababakar

**Comment by madamic** [comment]
Hello,
These are not simulations, but real measurements with an actual Zynq device. You can produce these graphs in the 'Calibration' tab of the Matlab application. Matlab source code is available. This repository contains all the source code related to this project.
Cheers, Michel

**Comment by madamic** [comment]
Ohh, sorry, I was talking about different plots. These 'bubbles' in the delay line are also real measurements on a Zynq 7020 chip. They were done with the Integrated Logic Analyzer (ILA) core provided by Xilinx. You can add this core in the IP Integrator, upload the generated bitstream on the device and monitor signals in real-time via JTAG. I don't have the makefile for that, just google how to add ILA in the block design, it's pretty straightforward.
Best, Michel
